var nw_brand_val = {
	name : "nw",
	font_family_regular: "RNHouseSansRegular, sans-serif",
	tick_shelf_margin_top : "70px",
	tick_shelf_margin_bottom : "20px",
	tick_icon_width : "25px",
	tick_icon_height : "19px",
	tick_title_wrapper_width : "372px",
	tick_title_wrapper_bottom : "20px",
	tick_title_fs : "26px",
	tick_title_lh : "34px",
	tick_title_color : "rgba(66, 20, 95, 1)",
	tick_text_wrapper_width : "372px",
	tick_text_wrapper_bottom : "50px",
	tick_text_fs : "18px",
	tick_text_lh : "26px",
	tick_text_color : "rgba(51, 51, 51, 1)",
	tick_text_bottom : "50px",
	tick_shelf_margin_top_l : "60px",
	tick_shelf_margin_bottom_l : "10px",
	tick_icon_width_l : "25px",
	tick_icon_height_l : "19px",
	tick_title_wrapper_width_l : "292px",
	tick_title_wrapper_bottom_l : "20px",
	tick_title_fs_l : "24px",
	tick_title_lh_l : "32px",
	tick_title_color_l : "rgba(66, 20, 95, 1)",
	tick_text_wrapper_width_l : "292px",
	tick_text_wrapper_bottom_l: "50px",
	tick_text_fs_l : "18px",
	tick_text_lh_l : "26px",
	tick_text_color_l : "rgba(51, 51, 51, 1)",
	tick_text_bottom_l : "50px",
	tick_shelf_margin_top_m : "50px",
	tick_shelf_margin_bottom_m : "0px",
	tick_icon_width_m : "25px",
	tick_icon_height_m : "18.1px",
	tick_title_wrapper_width_m : "281px",
	tick_title_wrapper_bottom_m : "20px",
	tick_title_fs_m : "24px",
	tick_title_lh_m : "32px",
	tick_title_color_m : "rgba(66, 20, 95, 1)",
	tick_text_wrapper_width_m : "281px",
	tick_text_wrapper_bottom_m: "50px",
	tick_text_fs_m : "18px",
	tick_text_lh_m : "26px",
	tick_text_color_m : "rgba(51, 51, 51, 1)",
	tick_text_bottom_m : "50px",
	tick_shelf_margin_top_s : "50px",
	tick_shelf_margin_bottom_s : "10px",
	tick_icon_width_s : "20px",
	tick_icon_height_s : "14.5px",
	tick_title_wrapper_width_s : "276px",
	tick_title_wrapper_bottom_s : "20px",
	tick_title_fs_s : "24px",
	tick_title_lh_s : "32px",
	tick_title_color_s : "rgba(66, 20, 95, 1)",
	tick_text_wrapper_width_s : "276px",
	tick_text_wrapper_bottom_s: "40px",
	tick_text_fs_s : "18px",
	tick_text_lh_s : "26px",
	tick_text_color_s : "rgba(51, 51, 51, 1)",
	tick_text_bottom_s : "40px"
}

module.exports = {
	nw_brand : nw_brand_val
}